### ISSUE TITLE
unexpected error claiming task

### ISSUE THREAD

**Issue by AlonGluz** [CircleCI-Public/circleci-runner-k8s#15]
I'm seeing this error in the log:  _https://runner.circleci.com/api/v2/runner/claim\": net/http: invalid header field value_ after applying the helm chart

**Comment by jrahme-cci** [comment]
Hi @AlonGluz , are you still seeing this issue occur? I'll be closing the issue soon as needing more details soon, so if you are able to get us a link to the job to help us investigate the issue it'd be greatly appreciated. 

Cheers,

Jacob

**Comment by jrahme-cci** [comment]
Issue closed as no further details were provided to investigate with.
